services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\MailerModule\ZikulaMailerModule'

    Zikula\MailerModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\MailerModule\Api\ApiInterface\MailerApiInterface: '@Zikula\MailerModule\Api\MailerApi'

    Zikula\MailerModule\Api\MailerApi:
        arguments:
          $installed: '%installed%'
