services:
    zikula_mailer_module.container.link_container:
        class: Zikula\MailerModule\Container\LinkContainer
        arguments:
          - "@translator.default"
          - "@router"
          - "@zikula_permissions_module.api.permission"
        tags:
            - { name: zikula.link_container }

    zikula_mailer_module.api.mailer:
        class: Zikula\MailerModule\Api\MailerApi
        arguments:
          - "%installed%"
          - "@kernel"
          - "@translator.default"
          - "@event_dispatcher"
          - "@zikula.dynamic_config_dumper"
          - "@zikula_extensions_module.api.variable"
          - "@mailer"

    zikula_mailer_module.hook_subscriber.ui_hooks_subscriber:
        class: Zikula\MailerModule\HookSubscriber\UiHooksSubscriber
        arguments:
          - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'mailer.ui_hooks.htmlmail.form_edit' }
