##
# ZikulaAtomTheme variables
##
showdescription:
  default_value: true
  type: 'Symfony\Component\Form\Extension\Core\Type\CheckboxType'
  options:
    label: "Show item descriptions"
    disabled: true
