services:
    zikula_search_module.container.link_container:
        class: Zikula\SearchModule\Container\LinkContainer
        arguments:
          - "@translator.default"
          - "@jms_i18n_routing.router"
          - "@zikula_permissions_module.api.permission"
          - "@zikula_users_module.current_user"
        tags:
            - { name: zikula.link_container }

    zikula_search_module.form.type.block.search:
        class: Zikula\SearchModule\Block\Form\Type\SearchBlockType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    twig.extension.zikula_search_module:
        class: Zikula\SearchModule\Twig\TwigExtension
        public: false
        arguments: ["@zikula_extensions_module.api.variable"]
        tags:
            - { name: twig.extension }

    zikula_search_module.front_controller_listener:
        class: Zikula\SearchModule\Listener\FrontControllerListener
        arguments:
          - "@router"
          - "@zikula_permissions_module.api.permission"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_core.common.theme.assets_header"
          - "%installed%"
          - "@=container.hasParameter('upgrading') ? parameter('upgrading') : false"
        tags:
            - { name: kernel.event_subscriber }

    zikula_search_module.module_event_listener:
        class: Zikula\SearchModule\Listener\ModuleEventListener
        tags:
            - { name: kernel.event_subscriber }

    zikula_search_module.internal.searchable_module_collector:
        class: Zikula\SearchModule\Collector\SearchableModuleCollector
