imports:
    - { resource: parameters.yml }
#    - { resource: security.yml }

framework:
    #esi:             ~
#    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: true
        proxy_namespace: Proxies
        proxy_dir: %kernel.cache_dir%/doctrine/orm/Proxies
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                connection: default
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree
                    zikula_core_entities:
                        type: annotation
                        dir: %kernel.root_dir%/../src
                        is_bundle: false
                        prefix: Zikula
                    zikula_group_entities:
                        type: annotation
                        dir: %kernel.root_dir%/../web/system
                        is_bundle: false
                        prefix: Group
                    zikula_permission_entities:
                        type: annotation
                        dir: %kernel.root_dir%/../web/system
                        is_bundle: false
                        prefix: Permission
                    zikula_theme_entities:
                        type: annotation
                        dir: %kernel.root_dir%/../web/system
                        is_bundle: false
                        prefix: Theme
                    zikula_admin_entities:
                        type: annotation
                        dir: %kernel.root_dir%/../web/system
                        is_bundle: false
                        prefix: Admin
                    zikula_block_entities:
                        type: annotation
                        dir: %kernel.root_dir%/../web/system
                        is_bundle: false
                        prefix: Block
                    zikula_user_entities:
                        type: annotation
                        dir: %kernel.root_dir%/../web/system
                        is_bundle: false
                        prefix: User
                    zikula_search_entities:
                        type: annotation
                        dir: %kernel.root_dir%/../web/system
                        is_bundle: false
                        prefix: Search
                    zikula_security_entities:
                        type: annotation
                        dir: %kernel.root_dir%/../web/system
                        is_bundle: false
                        prefix: Security
                metadata_cache_driver: array
                query_cache_driver: array

stof_doctrine_extensions:
    #default_locale: en
    orm:
        #default: ~
        default:
            tree:           true
            timestampable:  true
            sluggable:      true
            translatable:   true
            loggable:       false
            softdeleteable: false
#    class:
#        tree:           ~
#        timestampable:  ~
#        sluggable:      ~
#        translatable:   ~
#        loggable:       ~
#        softdeleteable: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# JMS I18n Routing http://jmsyst.com/bundles/JMSI18nRoutingBundle/master/configuration
#jms_i18n_routing:
#    default_locale: en
#    locales: [en, de]
#    strategy: prefix
