services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\ZAuthModule\ZikulaZAuthModule'

    Zikula\ZAuthModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\ZAuthModule\Helper\:
        resource: '../../Helper/*'
        lazy: true

    Zikula\ZAuthModule\Api\ApiInterface\PasswordApiInterface: '@Zikula\ZAuthModule\Api\PasswordApi'
    Zikula\ZAuthModule\Entity\RepositoryInterface\AuthenticationMappingRepositoryInterface: '@Zikula\ZAuthModule\Entity\Repository\AuthenticationMappingRepository'
    Zikula\ZAuthModule\Entity\RepositoryInterface\UserVerificationRepositoryInterface: '@Zikula\ZAuthModule\Entity\Repository\UserVerificationRepository'

    Zikula\ZAuthModule\Api\UserCreationApi:
        public: true #temp
