monolog:
    channels: ['mail', 'zikula']
    handlers:
        mail:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.mail.log"
            level: debug
            channels: ["mail"]
        zikula:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.zikula.log"
            level: debug
            channels: ["zikula"]
        mail:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.mail.log"
            level: debug
            channels: ["mail"]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!mail"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
