# The configuration specified in here might be overwritten by the dynamically generated configuration in
# generated.yaml
# It's here to give an initial configuration (until Zikula is installed).

jms_i18n_routing:
    strategy: prefix_except_default
# this value must be changed reflecting the intended destination bundle of the maker
parameters:
    localisation.locales: [en]
    # multisites configuration does nothing unless the Multisites module is installed and configured properly.
    multisites:
        enabled: false
        mainsiteurl: ~
        based_on_domains: ~
        protected.systemvars: []
translation:
    configs:
        zikula:
            dirs: [] # will be set dynamically
            output_dir: '%kernel.project_dir%/translations'
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [vendor, cache, data, log]
            output_format: yaml
            local_file_storage_options:
                default_output_format: yaml
        extension:
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [vendor]
            output_format: yaml
            local_file_storage_options:
                default_output_format: yaml
