parameters:
    zikula_users_module.internal.authentication_method_collector.class: Zikula\UsersModule\Collector\AuthenticationMethodCollector
    zikula_users_module.form.default_registration_type.class: Zikula\UsersModule\Form\RegistrationType\DefaultRegistrationType
    zikula_users_module.form.default_login_type.class: Zikula\UsersModule\Form\Type\DefaultLoginType

services:
    zikula_users_module.internal.authentication_method_collector:
        class: %zikula_users_module.internal.authentication_method_collector.class%
        arguments: ["@zikula_extensions_module.api.variable"]

    zikula_users_module.form.default_registration_type:
        class: %zikula_users_module.form.default_registration_type.class%
        arguments: ["@translator.default"]
        tags:
            - { name: form.type, alias: "Zikula\UsersModule\Form\RegistrationType\DefaultRegistrationType" }

    zikula_users_module.form.default_login_type:
        class: %zikula_users_module.form.default_login_type.class%
        arguments: ["@translator.default"]
        tags:
            - { name: form.type, alias: "Zikula\UsersModule\Form\Type\DefaultLoginType" }
