imports:
    - { resource: config.yml }
    - { resource: 'packages/dev/php_translation.yaml' }

framework:
    router:   { resource: '%kernel.project_dir%/config/routing_dev.yml' }
    profiler: { only_exceptions: false }

maker:
    # this value must be changed reflecting the intended destination bundle of the maker
    root_namespace: 'Zikula\ExtensionsModule'

web_profiler:
    toolbar: '%debug%'
    intercept_redirects: false
    excluded_ajax_paths:  '^/((index|app(_[\w]+)?)\.php/)?_wdt'

monolog:
    handlers:
        main:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

web_profiler_extra:
    routing:
        enabled:        false
        display_in_wdt: true
    container:
        enabled:        false
        display_in_wdt: true
    twig:
        enabled:        false
        display_in_wdt: true
    assetic:
        enabled:        false
        display_in_wdt: false
