services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $bundle: '@Zikula\ThemeModule\ZikulaThemeModule'
            $installed: '%installed%'

    Zikula\ThemeModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

  # public because CoreInstallerBundle::AbstractController accesses this using container
    Zikula\ThemeModule\Helper\:
        resource: '../../Helper/*'
        public: true
        lazy: true

    Zikula\ThemeModule\Api\ApiInterface\PageAssetApiInterface: '@Zikula\ThemeModule\Api\PageAssetApi'
    Zikula\ThemeModule\Entity\RepositoryInterface\ThemeEntityRepositoryInterface: '@Zikula\ThemeModule\Entity\Repository\ThemeEntityRepository'

    # public because ThemeModuleInstaller uses it
    Zikula\ThemeModule\Entity\Repository\ThemeEntityRepository:
        public: true

    # public because installer accesses this using container
    Zikula\ThemeModule\Helper\BundleSyncHelper:
        public: true

    Zikula\ThemeModule\Twig\Extension\PageVarExtension:
        arguments:
            $pageVars: '@zikula_core.common.theme.pagevars'

    # public because ZikulaKernel accesses this using container
    Zikula\ThemeModule\Engine\Engine:
        public: true

    zikula_core.common.theme.assets_js:
        class: Zikula\ThemeModule\Engine\AssetBag
    # public because AbstractBundle accesses this using container
    zikula_core.common.theme.assets_css:
        class: Zikula\ThemeModule\Engine\AssetBag
        public: true
    zikula_core.common.theme.assets_header:
        class: Zikula\ThemeModule\Engine\AssetBag
    zikula_core.common.theme.assets_footer:
        class: Zikula\ThemeModule\Engine\AssetBag

    Zikula\ThemeModule\Api\PageAssetApi:
        arguments:
          $styleSheets: '@zikula_core.common.theme.assets_css'
          $scripts: '@zikula_core.common.theme.assets_js'
          $headers: '@zikula_core.common.theme.assets_header'
          $footers: '@zikula_core.common.theme.assets_footer'

    zikula_core.common.theme.pagevars:
        class: Zikula\ThemeModule\Engine\ParameterBag

    Zikula\ThemeModule\Engine\AssetFilter:
        arguments:
          $headers: '@zikula_core.common.theme.assets_header'
          $footers: '@zikula_core.common.theme.assets_footer'
          $js: '@Zikula\ThemeModule\Engine\Asset\JsResolver'
          $css: '@Zikula\ThemeModule\Engine\Asset\CssResolver'
          $scriptPosition: '%script_position%'

    zikula_core.common.theme.themevars:
        class: Zikula\ThemeModule\Engine\ParameterBag
        public: true

    # public because AbstractBundle accesses this using container
    Zikula\ThemeModule\Engine\Asset:
        public: true

    Zikula\ThemeModule\Engine\Asset\Merger:
        arguments:
          $jsCache: '@doctrine_cache.providers.zikula_js_asset_cache'
          $cssCache: '@doctrine_cache.providers.zikula_css_asset_cache'
          $kernelProjectDir: '%kernel.project_dir%'
          $lifetime: '%zikula_asset_manager.lifetime%'
          $minify: '%zikula_asset_manager.minify%'
          $compress: '%zikula_asset_manager.compress%'

    Zikula\ThemeModule\Engine\Asset\JsResolver:
        arguments:
          $bag: '@zikula_core.common.theme.assets_js'
          $env: '%env%'
          $combine: '%zikula_asset_manager.combine%'

    Zikula\ThemeModule\Engine\Asset\CssResolver:
        arguments:
          $bag: '@zikula_core.common.theme.assets_css'
          $env: '%env%'
          $combine: '%zikula_asset_manager.combine%'

    # override TwigBundle's Twig\Environment definition with Zikula's own child class
    # see vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml
    twig:
        class: Zikula\ThemeModule\Bridge\Twig\EventEnabledTwigEngine
        public: true
        arguments:
          $loader: '@twig.loader'
          $options: []
        calls:
          - [setEventDispatcher, ['@event_dispatcher']]
          - [addGlobal, ['pagevars', '@zikula_core.common.theme.pagevars']]
          - [addGlobal, ['themevars', '@zikula_core.common.theme.themevars']]
          - [addGlobal, ['currentUser', '@Zikula\UsersModule\Api\ApiInterface\CurrentUserApiInterface']]
          - [addRuntimeLoader, ['@twig.runtime_loader']]
        configurator: ['@twig.configurator.environment', 'configure']
    Twig_Environment: '@twig'
    Twig\Environment: '@twig'

    Zikula\ThemeModule\EventListener\CreateThemedResponseListener:
        tags:
            - { name: monolog.logger, channel: request }

    Zikula\ThemeModule\EventListener\DefaultPageAssetSetterListener:
        arguments:
          $jsAssetBag: '@zikula_core.common.theme.assets_js'
          $cssAssetBag: '@zikula_core.common.theme.assets_css'
          $env: '%env%'
          $bootstrapJavascriptPath: '%zikula.javascript.bootstrap.min.path%'
          $bootstrapFontAwesomeStylesheetPath: '%zikula.stylesheet.bootstrap-font-awesome.path%'
          $fontAwesomePath: '%zikula.stylesheet.fontawesome.min.path%'
          $bootstrapStylesheetPath: "@=container.hasParameter('zikula.stylesheet.bootstrap.min.path') ? parameter('zikula.stylesheet.bootstrap.min.path') : ''"
        tags:
            - { name: monolog.logger, channel: request }

    Zikula\ThemeModule\EventListener\DefaultPageVarSetterListener:
        arguments:
          $pageVars: '@zikula_core.common.theme.pagevars'
        tags:
            - { name: monolog.logger, channel: request }

    Zikula\ThemeModule\EventListener\ControllerAnnotationReaderListener:
        tags:
            - { name: monolog.logger, channel: request }

    Zikula\ThemeModule\EventListener\TemplatePathOverrideListener:
        arguments:
          $loader: '@twig.loader'
        tags:
            - { name: monolog.logger, channel: request }

    Zikula\ThemeModule\EventListener\AddJSConfigListener:
        arguments:
          $headers: '@zikula_core.common.theme.assets_header'
          $defaultSessionName: '%zikula.session.name%'

    Zikula\ThemeModule\EventListener\TemplateNameExposeListener:
        arguments:
          $env: '%env%'

    Zikula\ThemeModule\EventListener\ExtensionInstallationListener:
        arguments:
          $active: '%zikula_asset_manager.combine%'
