services:
    # Form field types
    
    zikula_routes_module.form.type.field.datetime:
        class: Zikula\RoutesModule\Form\Type\Field\DateTimeType
        tags:
            - { name: form.type }
    
    zikula_routes_module.form.type.field.multilist:
        class: Zikula\RoutesModule\Form\Type\Field\MultiListType
        arguments:
            - "@zikula_routes_module.listentries_helper"
        tags:
            - { name: form.type }
    
    zikula_routes_module.form.type.field.user:
        class: Zikula\RoutesModule\Form\Type\Field\UserType
        arguments:
            - "@zikula_users_module.user_repository"
        tags:
            - { name: form.type }
