services:
    # Helper classes
    zikula_routes_module.controller_helper:
        class: Zikula\RoutesModule\Helper\ControllerHelper
        arguments:
            - "@request_stack"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_routes_module.entity_factory"
            - "@zikula_routes_module.model_helper"
            - "@zikula_routes_module.selection_helper"

    zikula_routes_module.listentries_helper:
        class: Zikula\RoutesModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"

    zikula_routes_module.model_helper:
        class: Zikula\RoutesModule\Helper\ModelHelper
        arguments:
            - "@zikula_routes_module.entity_factory"

    zikula_routes_module.selection_helper:
        class: Zikula\RoutesModule\Helper\SelectionHelper
        arguments:
            - "@translator.default"
            - "@zikula_routes_module.entity_factory"

    zikula_routes_module.view_helper:
        class: Zikula\RoutesModule\Helper\ViewHelper
        arguments:
            - "@templating"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.common.theme.pagevars"
            - "@zikula_routes_module.controller_helper"
        calls:
            - method: setAdditionalDependencies
              arguments:
                - "@translator.default"
                - "@zikula.dynamic_config_dumper"
                - "@zikula_extensions_module.extension_repository"

    zikula_routes_module.workflow_helper:
        class: Zikula\RoutesModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@zikula_routes_module.listentries_helper"
