services:
    zikula_routes_module.link_container:
        class: Zikula\RoutesModule\Container\LinkContainer
        arguments: ["@translator.default", "@router", "@zikula_permissions_module.api.permission", "@zikula_routes_module.controller_helper"]
        tags:
            - { name: zikula.link_container }
