##
# ZikulaAndreas08Theme config
##
admin:
  page: ":admin.html.twig"
  block:
    positions:
      left: "Block:block.html.twig"
      right: "Block:block.html.twig"
      center: "Block:block.html.twig"
      topnav: "Block:topnavblock.html.twig"
      search: "Block:searchblock.html.twig"
home:
  page: ":home.html.twig"
  block:
    positions:
      left: "Block:block.html.twig"
      right: "Block:block.html.twig"
      center: "Block:block.html.twig"
      topnav: "Block:topnavblock.html.twig"
      search: "Block:searchblock.html.twig"
master:
  page: ":master.html.twig"
  block:
    positions:
      left: "Block:block.html.twig"
      right: "Block:block.html.twig"
      center: "Block:block.html.twig"
      topnav: "Block:topnavblock.html.twig"
      search: "Block:searchblock.html.twig"
