# The configuration specified in here might be overwritten by the dynamically generated configuration in
# generated.yml
# It's here to give an initial configuration (until Zikula is installed).

jms_i18n_routing:
    default_locale: en
    locales: [en]
    strategy: prefix_except_default
swiftmailer:
    transport: null
    username: ''
    password: ''
    host: 'localhost'
    port: 25
    encryption: null
    auth_mode: null
    delivery_addresses: []
    disable_delivery: true
parameters:
    zikula.session.name: _zsid
    # multisites configuration does nothing unless the Multisites module is installed and configured properly.
    multisites:
        enabled: false
        mainsiteurl: ~
        based_on_domains: ~
        protected.systemvars: []
