parameters:
    installed:        false
    env:              prod
    debug:            false
    script_position:  foot
    # script_position defines the location where javascripts will be placed in the page
    # choices are `head` or `foot`
    temp_dir:         %kernel.cache_dir%/ztemp
    datadir:          userdata
    system.chmod_dir: 0777

    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     ~
    database_user:     ~
    database_password: ~
    database_path:     ~
    database_socket:   ~
    database_server_version: 5
    # _actual_ server version doesn't matter here. Any value compensates for Doctrine Bug DBAL-1057
    # see https://github.com/doctrine/dbal/issues/990
    # the actual value is written on install

    pagerendertime:    false

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    url_secret:        ~

    zikula.session.name: _zsid
    assets_version: ~ #e.g. 'v1'
    zikula_asset_manager.combine: true
    zikula_asset_manager.lifetime: "1 day"
    zikula_asset_manager.compress: true
    zikula_asset_manager.minify: true

    # Changing the current umask to the octal "022" will set directory permissions
    # to "755", and file permissions to "644" (for directories such as
    # "app/cache" and "app/logs"). Changing the current umask to the octal "02"
    # will set directory permissions to "775", and file permissions to "664".
    # Changing the current umask to the octal "0" will set (insecure) directory
    # permissions to "777", and file permissions to "666". Note that using the ACL
    # is recommended when you have access to them on your server, because changing
    # the umask is not thread-safe. Set this value to "~" (NULL), to disable support
    # for umask.
    umask:             ~

    # the following parameter is used in the clickjacking protection listener
    # it accepts any values allowed for X-Frame-Options
    security.x_frame_options: SAMEORIGIN
