_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix:   /_error

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

# This would need the JMSDiExtraBundle
# http://jmsyst.com/bundles/JMSTranslationBundle/master/webinterface#installation
#JMSTranslationBundle_ui:
#    resource: @JMSTranslationBundle/Controller/
#    type:     annotation
#    prefix:   /_trans

_main:
    resource: routing.yml
