core:
    resource: "@CoreBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

installer:
    resource: "@ZikulaCoreInstallerBundle/Resources/config/routing/routing.xml"

Routing:
    resource: .
    type: zikularoutesmodule
