core:
    resource: "@CoreBundle/Resources/config/routing.xml"

hook:
    resource: "@ZikulaHookBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

installer:
    resource: "@ZikulaCoreInstallerBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# Note: if you want to add routes for a native Symfony bundle
# insert them here and not below the "Routing" and "legacy" entries

Routing:
    resource: .
    type: zikularoutesmodule
