Routing:
    resource: .
    type: zikularoutesmodule

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

installer:
    resource: "@ZikulaCoreInstallerBundle/Resources/config/routing/routing.xml"
