services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true # default to public because installer still uses container directly

    Zikula\Bundle\CoreInstallerBundle\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\Bundle\CoreInstallerBundle\Command\Install\StartCommand:
        arguments:
            $installed: '%installed%'

    Zikula\Bundle\CoreInstallerBundle\Command\Install\FinishCommand:
        arguments:
            $installed: '%installed%'

    Zikula\Bundle\CoreInstallerBundle\Helper\ParameterHelper:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Zikula\Bundle\CoreInstallerBundle\Helper\CacheHelper:
        arguments:
            $symfonyCacheClearer: '@cache_clearer'

    Zikula\Bundle\CoreInstallerBundle\EventListener\InstallUpgradeCheckListener:
        arguments:
            $installed: '%installed%'
            $currentVersion: '%core_installed_version%' # ZikulaKernel::CORE_INSTALLED_VERSION_PARAM
