name: Update dependencies
on:
  schedule:
    - cron:  '0 */12 * * *' # run every 12 hours
jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources from 3.0 branch
      uses: actions/checkout@v2
      with:
        ref: '3.0'

    # persist composer's internal cache directory to reduce the workflow execution time
    - name: Get Composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    # use composer 1
    # TODO get rid of this
    - name: Install dependencies
      run: |
        wget https://getcomposer.org/composer-1.phar
        chmod +x composer-1.phar
        ./composer-1.phar install

    #- name: Install dependencies
      #run: |
        #composer install

    - name: Update dependencies
      #run: |
      #  php -dmemory_limit=10G /usr/bin/composer update
      run: |
        ./composer-1.phar config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
        ./composer-1.phar update
        ./composer-1.phar config --global --auth --unset github-oauth.github.com
        rm ./composer-1.phar
      #run: |
        #composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
        #composer update
        #composer config --global --auth --unset github-oauth.github.com

    # see https://github.com/peter-evans/create-pull-request
    - name: Commit changes and create/update pull request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'update dependencies :balloon:'
        title: Vendor update
        body: This is an auto-generated PR with dependency updates.
        labels: dep-updates
        branch: dep-updates
        base: '3.0'

    - name: Check outputs
      run: |
        echo "Pull Request Number: ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"
