name: Update dependencies
on:
  schedule:
    - cron:  '0 */12 * * *' # run every 12 hours
jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources from main branch
      uses: actions/checkout@v2
      with:
        ref: main

    # persist composer's internal cache directory to reduce the workflow execution time
    - name: Get Composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        php7.4 /usr/bin/composer install

    - name: Update dependencies
      run: |
        composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
        php7.4 /usr/bin/composer update
        composer config --global --auth --unset github-oauth.github.com

    # see https://github.com/peter-evans/create-pull-request
    - name: Commit changes and create/update pull request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'update dependencies :balloon:'
        title: Vendor update
        body: This is an auto-generated PR with dependency updates.
        labels: dep-updates
        branch: dep-updates

    - name: Check outputs
      run: |
        echo "Pull Request Number: ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"
